// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const request = require('supertest');
const express = require('express');
const path = require('path');
const app = express();
const bodyParser = require("body-parser")

describe('Server Test Suite', () => {
    
    beforeAll(() => {
        app.listen(3000, () => {
            console.log(`Server listening on the port::${3000}`);
        })
    });

    test('should start server at given port', async () => {
        request(app)
        .get('/')
        .then(response => {
            expect(response.statusCode).toBe(200);
        })
    });

    test('should fail to start server at invalid port', () => {
        expect(() => {
            app.listen('invalidPort', () => {
                console.log(`Server listening on the port::invalidPort`);
            })
        }).toThrow();
    });

    afterAll(() => {
        app.close();
    });
});
