// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const { src, dest, series, parallel } = require('gulp');
const del = require('del');
const fs   = require('fs');
const zip = require('gulp-zip');
const log = require('fancy-log');
const webpack_stream = require('webpack-stream');
const webpack_config = require('./webpack.config.js');
var exec = require('child_process')
const copyReactCodeTask = require('../gulpfile.js').copyReactCodeTask;

describe('copyReactCodeTask function', () => {
    beforeEach(() => {
        // Mock log function
        log.mockImplementation(() => {});
    });

    afterEach(() => {
        // Restore original log function
        log.mockRestore();
    });

    test('it should log the correct message', () => {
        copyReactCodeTask();
        expect(log).toHaveBeenCalledWith('copying React code into the directory');
    });

    test('it should call src with correct arguments', () => {
        const srcSpy = jest.spyOn(src, 'src');
        copyReactCodeTask();
        expect(srcSpy).toHaveBeenCalledWith(`${paths.react_src}`);
    });

    test('it should call dest with correct arguments', () => {
        const destSpy = jest.spyOn(dest, 'dest');
        copyReactCodeTask();
        expect(destSpy).toHaveBeenCalledWith(`${paths.react_dist}`);
    });
});
