// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const request = require('supertest');
const express = require('express');
const app = require('./server');

describe('Test the root path', () => {
  test('It should respond to the GET method', async () => {
    const response = await request(app).get('/');
    expect(response.statusCode).toBe(200);
  });

  test('It should respond with a message Server listening on the port::${port}', async () => {
    const port = 3000;
    const consoleSpy = jest.spyOn(console, 'log');
    app.listen(port, () => {});
    expect(consoleSpy).toHaveBeenCalledWith(`Server listening on the port::${port}`);
  });
});
