// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const { buildReactCodeTask } = require('./gulpfile');
const exec = require('child_process').exec;

jest.mock('child_process', () => {
  return {
    exec: jest.fn((command, callback) => callback(null, 'stdout', 'stderr'))
  };
});

describe('Build React Code Task', () => {
  beforeAll(() => {
    jest.clearAllMocks();
  });

  test('should build react code successfully', (done) => {
    exec.mockImplementation((command, callback) => callback(null, 'stdout', 'stderr'));
    buildReactCodeTask((err) => {
      expect(err).toBeNull();
      expect(exec).toBeCalledWith('cd ../my-app && npm run build', expect.any(Function));
      done();
    });
  });

  test('should throw error when building react code fails', (done) => {
    const error = new Error('Building failed');
    exec.mockImplementation((command, callback) => callback(error, 'stdout', 'stderr'));
    buildReactCodeTask((err) => {
      expect(err).toEqual(error);
      expect(exec).toBeCalledWith('cd ../my-app && npm run build', expect.any(Function));
      done();
    });
  });
});
