// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const { clean } = require('./gulpfile');
const mock = require('mock-fs');

describe('clean function', () => {
  beforeEach(() => {
    mock({
      '../prod-build': {
        'file1.txt': 'file content here',
        'file2.txt': 'file content here'
      },
    });
  });

  afterEach(mock.restore);

  test('should remove all files in the directory', async () => {
    await clean();
    expect(fs.existsSync('../prod-build/file1.txt')).toBe(false);
    expect(fs.existsSync('../prod-build/file2.txt')).toBe(false);
  });

  test('should log the operation', () => {
    console.log = jest.fn();
    clean();
    expect(console.log).toHaveBeenCalledWith('removing the old files in the directory');
  });

  test('should not throw error when directory is already empty', async () => {
    await clean();
    expect(async () => {
      await clean();
    }).not.toThrow();
  });
});
