// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4


const { src, dest, series, parallel } = require('gulp');
const del = require('del');
const fs   = require('fs');
const zip = require('gulp-zip');
const log = require('fancy-log');
const webpack_stream = require('webpack-stream');
const webpack_config = require('./webpack.config.js');
const exec = require('child_process')
const { copyReactCodeTask } = require('./gulpfile');

describe('copyReactCodeTask function', () => {
  let paths;

  beforeEach(() => {
    paths = {
      react_src: 'src/react',
      react_dist: 'dist/react'
    };
  });

  test('should copy React code into the directory', () => {
    expect.assertions(1);
    
    const srcSpy = jest.spyOn(gulp, 'src').mockImplementation(() => ({
      pipe: jest.fn()
    }));
    
    copyReactCodeTask();
    expect(srcSpy).toHaveBeenCalledWith(`${paths.react_src}`);
    srcSpy.mockRestore();
  });
  
  test('should throw error when source path is not found', () => {
    paths.react_src = 'nonexistent/path';
    expect(copyReactCodeTask).toThrow();
  });
  
  afterEach(() => {
    jest.clearAllMocks();
  });
});
