// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4



const { src, dest, series, parallel } = require('gulp');
const del = require('del');
const fs   = require('fs');
const zip = require('gulp-zip');
const log = require('fancy-log');
const webpack_stream = require('webpack-stream');
const webpack_config = require('./webpack.config.js');
var exec = require('child_process')

describe('copyNodeJSCodeTask function', () => {
  let paths;

  beforeEach(() => {
    paths = {
      prod_build: './prod_build'
    };
  });

  test('should log the correct message', () => {
    const logSpy = jest.spyOn(log, 'log');
    copyNodeJSCodeTask();
    expect(logSpy).toHaveBeenCalledWith('building and copying server code into the directory');
  });

  test('should call webpack_stream with the correct argument', () => {
    const webpack_streamSpy = jest.spyOn(webpack_stream, 'webpack_stream');
    copyNodeJSCodeTask();
    expect(webpack_streamSpy).toHaveBeenCalledWith(webpack_config);
  });

  test('should call dest with the correct argument', () => {
    const destSpy = jest.spyOn(dest, 'dest');
    copyNodeJSCodeTask();
    expect(destSpy).toHaveBeenCalledWith(`${paths.prod_build}`);
  });
});

function copyNodeJSCodeTask() {
  log('building and copying server code into the directory');
  return webpack_stream(webpack_config).pipe(dest(`${paths.prod_build}`));
}

